In [1]:
import numpy as np
np.random.seed(0) # seed for reproducibility

In [7]:
x1 = np.random.randint(10, size=6)         # 1D array
x2 = np.random.randint(10, size=(3, 4))    # 2D array
x3 = np.random.randint(10, size=(3, 4, 5)) # 3D array

In [8]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [9]:
print("dtype", x3.dtype)

dtype int32


In [10]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [11]:
x1

array([8, 5, 9, 0, 9, 6])

In [12]:
x1[0]

8

In [13]:
x1[-1]

6

In [14]:
x1[-2]

9

In [15]:
x2

array([[5, 3, 1, 8],
       [0, 4, 9, 6],
       [5, 7, 8, 8]])

In [16]:
x2[0, 0]

5

In [20]:
x2[0, 3]

8

In [21]:
x2[0, 3] = 12

In [22]:
x2

array([[ 5,  3,  1, 12],
       [ 0,  4,  9,  6],
       [ 5,  7,  8,  8]])

In [25]:
x1[0] = 3.142 # this will be truncated! round to nearest number for int

In [26]:
x1

array([3, 5, 9, 0, 9, 6])